services:
  nginx:
    build:
      context: nginx
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - node-network
    restart: always
    depends_on:
      - node
      - db

  node:
    build:
      context: node
    container_name: node-app
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm run start"
    tty: true
    ports:
      - "3000:3000"
    networks:
      - node-network
    restart: always
    depends_on:
      - db
    
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge